name : Push kode ke EC2 image
on:
  push:
    branches: main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: AWS_environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Create Node Environment  # Sets up Node.js environment.
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x

      - name: Install Packages and Build Application  # Installs npm packages and builds the Vue.js application.
        run: |
          npm ci
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: coba
      - run: ls coba
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: coba

      # - name: "Configure AWS Credentials" 
      #   uses: aws-actions/configure-aws-credentials@v4.0.2
      #   with:
      #     aws-region: eu-north-1
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      # - name : Create Code Deploy
      #   id: deploy
      #   uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
      #   with:
      #         application: latihanCodedeploy
      # - name : Print Commit Message
      #   uses: peter-evans/commit-comment@v2
      #   with:
      #         application: latihanCodedeploy
      #         token: ${{ secrets.TOKEN_GITHUB }}
      #         body: |
      #               @${{ github.actor }} this was deployed as [${{ steps.deploy.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy.outputs.deploymentId }}?region=eu-north-1) to group `${{ steps.deploy.outputs.deploymentGroupName }}`.
            